line-length = 100
target-version = "py311"

[lint]
select = ["E", "F", "I", "UP", "B", "SIM"]
ignore = ["E501"]  # довгі рядки ігноруємо на MVP

[lint.per-file-ignores]
"alembic/*" = ["E402", "F401"]            # alembic env: нетопові/невикор. імпорти
"app/models/__init__.py" = ["F401"]       # side-effect імпорти для реєстрації моделей
"app/main.py" = ["F401"]                  # side-effect імпорти для реєстрації моделей
"app/schemas/__init__.py" = ["F401"]
